//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_PnP_Core_JavaScript.Layouts.SP_PnP_Core_JavaScript {
    
    
    public partial class PnPCoreJS {
    }
}
